export const USER_SIGNUP = "USER_SIGNUP";
export const RESTAURANT_SIGNUP = "RESTAURANT_SIGNUP";

export const USER_LOGIN = "USER_LOGIN";
export const RESTAURANT_LOGIN = "RESTAURANT_LOGIN";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_PROFILE = "USER_PROFILE";